site_name: Erlang LS
repo_name: erlang-ls/erlang_ls
repo_url: https://github.com/erlang-ls/erlang_ls
edit_uri: ''
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
nav:
  - Erlang LS: index.md
  - Features: features.md
  - Editors:
      - Emacs: editors/emacs.md
      - VSCode: editors/vscode.md
      - Sublime Text 3: editors/sublime3.md
      - IntelliJ: editors/intellij.md
      - Vim: editors/vim.md
      - Theia IDE: editors/theia.md
  - Troubleshooting: troubleshooting.md
