site_name: Erlang LS
repo_name: erlang-ls/erlang_ls
repo_url: https://github.com/erlang-ls/erlang_ls
edit_uri: ''
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
nav:
  - Overview: index.md
  - Features: features.md
  - Editors:
      - Emacs: editors/emacs.md
      - Spacemacs: editors/spacemacs.md
      - VSCode: editors/vscode.md
      - Sublime Text 3: editors/sublime3.md
      - IntelliJ: editors/intellij.md
      - Vim: editors/vim.md
      - Theia IDE: editors/theia.md
  - Configuration: configuration.md
  - Talks: talks.md
  - Articles:
      - "How To: Diagnostics": articles/tutorial-implementing-diagnostics.md
      - Suggesting Type Specs: articles/suggest-type-specs.md
      - Snippets are here: articles/snippets-are-here.md
      - OTP 23 Brings Docs: articles/otp-23-bring-docs.md
  - Troubleshooting: troubleshooting.md
  - Internals: internals.md
markdown_extensions:
  - admonition
